import time
import random
from turtle import Turtle, Screen
WIDTH = 800
HEIGHT = 600
PADDLE_AWAY = 30
PADDLE_POSITION_RIGHT = WIDTH/2 - PADDLE_AWAY
PADDLE_POSITION_LEFT = -WIDTH/2 + PADDLE_AWAY
SPEED = 0.05
STEPS = 20